/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	myresourcev1alpha1 "Kubewatch/pkg/apis/myresource/v1alpha1"
	versioned "Kubewatch/pkg/client/clientset/versioned"
	internalinterfaces "Kubewatch/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "Kubewatch/pkg/client/listers/myresource/v1alpha1"
	"context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// MyresourceInformer provides access to a shared informer and lister for
// Myresources.
type MyresourceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.MyresourceLister
}

type myresourceInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewMyresourceInformer constructs a new informer for Myresource type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewMyresourceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredMyresourceInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredMyresourceInformer constructs a new informer for Myresource type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredMyresourceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MathV1alpha1().Myresources(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MathV1alpha1().Myresources(namespace).Watch(context.TODO(), options)
			},
		},
		&myresourcev1alpha1.Myresource{},
		resyncPeriod,
		indexers,
	)
}

func (f *myresourceInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredMyresourceInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *myresourceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&myresourcev1alpha1.Myresource{}, f.defaultInformer)
}

func (f *myresourceInformer) Lister() v1alpha1.MyresourceLister {
	return v1alpha1.NewMyresourceLister(f.Informer().GetIndexer())
}
