/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "Kubewatch/pkg/apis/myresource/v1alpha1"
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMyresources implements MyresourceInterface
type FakeMyresources struct {
	Fake *FakeMathV1alpha1
	ns   string
}

var myresourcesResource = schema.GroupVersionResource{Group: "math.tatacommunications.com", Version: "v1alpha1", Resource: "myresources"}

var myresourcesKind = schema.GroupVersionKind{Group: "math.tatacommunications.com", Version: "v1alpha1", Kind: "Myresource"}

// Get takes name of the myresource, and returns the corresponding myresource object, and an error if there is any.
func (c *FakeMyresources) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Myresource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(myresourcesResource, c.ns, name), &v1alpha1.Myresource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Myresource), err
}

// List takes label and field selectors, and returns the list of Myresources that match those selectors.
func (c *FakeMyresources) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MyresourceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(myresourcesResource, myresourcesKind, c.ns, opts), &v1alpha1.MyresourceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.MyresourceList{ListMeta: obj.(*v1alpha1.MyresourceList).ListMeta}
	for _, item := range obj.(*v1alpha1.MyresourceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested myresources.
func (c *FakeMyresources) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(myresourcesResource, c.ns, opts))

}

// Create takes the representation of a myresource and creates it.  Returns the server's representation of the myresource, and an error, if there is any.
func (c *FakeMyresources) Create(ctx context.Context, myresource *v1alpha1.Myresource, opts v1.CreateOptions) (result *v1alpha1.Myresource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(myresourcesResource, c.ns, myresource), &v1alpha1.Myresource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Myresource), err
}

// Update takes the representation of a myresource and updates it. Returns the server's representation of the myresource, and an error, if there is any.
func (c *FakeMyresources) Update(ctx context.Context, myresource *v1alpha1.Myresource, opts v1.UpdateOptions) (result *v1alpha1.Myresource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(myresourcesResource, c.ns, myresource), &v1alpha1.Myresource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Myresource), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMyresources) UpdateStatus(ctx context.Context, myresource *v1alpha1.Myresource, opts v1.UpdateOptions) (*v1alpha1.Myresource, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(myresourcesResource, "status", c.ns, myresource), &v1alpha1.Myresource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Myresource), err
}

// Delete takes name of the myresource and deletes it. Returns an error if one occurs.
func (c *FakeMyresources) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(myresourcesResource, c.ns, name), &v1alpha1.Myresource{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMyresources) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(myresourcesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.MyresourceList{})
	return err
}

// Patch applies the patch and returns the patched myresource.
func (c *FakeMyresources) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Myresource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(myresourcesResource, c.ns, name, pt, data, subresources...), &v1alpha1.Myresource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Myresource), err
}
